<datafile>    ::= <record> <A>
<A> ::= <A> <record> | 
<record>      ::= <field> <B> .
<B> ::= <B> ; <field> | 
<field>       ::= <integer>  |  <string>
<integer>     ::= <digit> <C>
<C> ::= <C> <digit> |
<string>      ::= # <char> <D> #
<D> ::= <D> <char> |
<char>        ::= <letter>  |  <digit>
<letter>      ::= A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | V | W | X | Y | Z
<digit>       ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
